controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    omnidirectional_controller:
      type: omnidirectional_controllers/OmnidirectionalController

    omni_wheel_controller:
      type: omni_wheel_controller/OmniWheelController
    
simple_velocity_controller:
  ros__parameters:
    joints:
      - wheel1_joint
      - wheel2_joint
      - wheel3_joint

omnidirectional_controller:
  ros__parameters:
    wheel_names: 
      - wheel1_joint
      - wheel2_joint
      - wheel3_joint

    # robot_radius: 0.075
    # wheel_radius: 0.23
    robot_radius: 0.28867
    wheel_radius: 0.075

    gamma: 30.0 # angle between body fixed y axis and the normal of wheel3

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    odom_numeric_integration_method: runge_kutta2

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.25
    use_stamped_vel: false
    
omni_wheel_controller:
  ros__parameters:
    # omni_wheel_names: ['wheel1_joint', 'wheel2_joint', 'wheel3_joint']
    # omni_wheel_angle: [3.1415926535897931, -1.047197551, 1.047197551]

    omni_wheel_names: ['wheel1_joint', 'wheel2_joint', 'wheel3_joint']
    omni_wheel_angle: [3.1415926535897931, 1.047197551, -1.047197551]

    # omni_wheel_distance: 0.075
    # wheel_radius: 0.23

    omni_wheel_distance: 0.313195
    wheel_radius: 0.15

    odom_frame_id: odom
    base_frame_id: base_link

    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    velocity_rolling_window_size: 10
    publish_cmd: true

    # limits
    linear_x:
      has_velocity_limits: true
      has_acceleration_limits: true
      has_jerk_limits: true
      max_velocity: 1.0
      min_velocity: -1.0
      max_acceleration: 0.4
      min_acceleration: -0.4
      max_jerk: 0.5
      min_jerk: -0.5
    


    angular_z:
      has_velocity_limits: true
      has_acceleration_limits: true
      has_jerk_limits: true
      max_velocity: 1.5
      min_velocity: -1.5
      max_acceleration: 0.8
      min_acceleration: -0.8
      max_jerk: 0.5
      min_jerk: -0.5
